### ISSUE TITLE
Could not load library libcudnn_cnn_infer.so.8

### ISSUE THREAD

**Issue by monopoly-db** [facebookresearch/nougat#105]
On WSL Ubuntu 22.04.2 LTS, I had to create a link to /usr/lib/wsl/lib/libcuda.so.1 in .local/lib/pythonx.xx/site-packages/nvidia/cudnn/lib/ directory, where libcudnn_cnn_infer.so.8 was found to make it work. 

CUDA was already installed on my Ubuntu WSL Windows 11 installation.

**Comment by KangWooLee** [comment]
I have exactly the same issue. I just saw it is closed. What was the solution?? How did you fix it

**Comment by lukas-blecher** [comment]
The way I understood it, the solution was part of the first comment
> I had to create a link to /usr/lib/wsl/lib/libcuda.so.1 in .local/lib/pythonx.xx/site-packages/nvidia/cudnn/lib/ directory, where libcudnn_cnn_infer.so.8 was found to make it work.

**Comment by KangWooLee** [comment]
Thank you!
