### ISSUE TITLE
Plain text when calling API

### ISSUE THREAD

**Issue by Yashar78** [facebookresearch/nougat#113]
If I call the API ( nougat_api) to OCR a pdf and save it to a file and read it back , I see just a plain text, like 
_"and a \(1\times 1\) pointwise convolution 2(c).\n\nA standard convolutional layer takes as input a \(D_{F}\times D_{F}\times M\) feature map \(\mathbf{F}\) and produces a \(D_{F}\times D_{F}\times N\) feature map \(\mathbf{G}\) where \(D_{F}\) is the spatial width and height of a square input feature map1, \(M\) is" ,_ 

which if I open it via the VS Code plugin I just see this plain text and no rendering of it. While if I do the same but this time via the nougat cli, then it is perfect and I can see the rendered formulas. 

should I convert text to a specific format, which library ?

**Comment by lukas-blecher** [comment]
how do you save it?

**Comment by Yashar78** [comment]
after calling the API :
Path(output_file_name).write_text( response.text , encoding="utf-8")

**Comment by lukas-blecher** [comment]
try instead
`Path(output_file_name).write_text( response.json() , encoding="utf-8")`

**Comment by Yashar78** [comment]
It works now . Thanks a lot 👍
