### ISSUE TITLE
Nougat API does not detect Intel UHD Graphics 620 GPU On Linux (pop-os)

### ISSUE THREAD

**Issue by ChamkhiAnas** [facebookresearch/nougat#117]
Upon attempting to use the Nougat API, the following error message is displayed:

WARNING:root:No GPU found. Conversion on CPU is very slow.

However, when listing the PCI devices on the system, the following output is displayed:

root@pop-os:~$ lspci | grep VGA
00:02.0 VGA compatible controller: Intel Corporation UHD Graphics 620 (rev 07)

Therefore, the GPU is present on the system, but is not being detected by the Nougat API.

![image](https://github.com/facebookresearch/nougat/assets/59390833/3b30a64a-bc0d-4eb8-a109-a5f1145df2f6)

**Comment by lukas-blecher** [comment]
PyTorch only supports Nvidia GPUs and some AMD GPUs. That's why no GPU was found on your system
