### ISSUE TITLE
Rendering speed is too slow by using engrafo to call LaTexML 

### ISSUE THREAD

**Issue by liuliyang991206** [facebookresearch/nougat#123]
I used engrafo to call LaTexML. But the rendering speend is very slow. It takes about 1~2 minutes to rendering a html, which is unacceptable. Is there any way to speed up the rendering process?

**Comment by lukas-blecher** [comment]
Go to the engrafo repository if you're looking for was to speed up their pipeline.

**Comment by limaopeng1** [comment]
> > I used engrafo to call LaTexML. But the rendering speend is very slow. It takes about 1~2 minutes to rendering a html, which is unacceptable. Is there any way to speed up the rendering process?
> 
> Hello, May I know have you find ways to speedup the rendering pipeline?

I have the same problem, have you solved it?
