### ISSUE TITLE
Nougat is now available in 🤗 Transformers

### ISSUE THREAD

**Issue by NielsRogge** [facebookresearch/nougat#128]
Hi folks,

Thanks for the great model :) Nougat is now available in HF Transformers, it's similar to [Donut](https://huggingface.co/docs/transformers/model_doc/donut) which was already available.

Docs can be found here: https://huggingface.co/docs/transformers/main/en/model_doc/nougat

Models are on the hub: https://huggingface.co/models?other=nougat.

Tutorial notebooks for inference + fine-tuning can be found here: https://github.com/NielsRogge/Transformers-Tutorials/tree/master/Nougat.

A Gradio demo (hosted as a 🤗 Space) can be found here: https://huggingface.co/spaces/hf-vision/nougat-transformers

**Comment by lukas-blecher** [comment]
Awesome! thanks a lot for your work

**Comment by bp-high** [comment]
Hi @NielsRogge @lukas-blecher , I recently built an AI Research Buddy using Nougat , a discussion buddy when it comes to research papers on Arxiv or Acl Anthology. Would love your feedback on this.
Video:- https://www.youtube.com/watch?v=c3Ae7DBuE-U
Github:- https://github.com/bp-high/research_buddy
HF Spaces Link:- https://huggingface.co/spaces/bpHigh/AI-Research-Buddy
This was built for the StreamLit LLM Hackathon (https://streamlit.io/community/llm-hackathon-2023)

Built using [Modal Labs](https://www.linkedin.com/company/modal-labs/) , [Clarifai](https://www.linkedin.com/company/clarifai/), [LlamaIndex](https://www.linkedin.com/company/llamaindex/), [LangChain](https://www.linkedin.com/company/langchain/), [OpenAI](https://www.linkedin.com/company/openai/), [Streamlit](https://www.linkedin.com/company/streamlit/) and ofcourse Nougat by [Meta Facebook](https://www.linkedin.com/company/metafacebook/) .

Deployed on [Hugging Face](https://www.linkedin.com/company/huggingface/) .
