### ISSUE TITLE
nougat DocVQA

### ISSUE THREAD

**Issue by DhavalWI** [facebookresearch/nougat#129]
as said nougat is similar in architecture to Donut. How do we create the docvqa model which donut has showed to be the best at using nougat? 

Can you please help me in the right direction?

**Comment by NielsRogge** [comment]
See my notebooks here: https://github.com/NielsRogge/Transformers-Tutorials/tree/master/Donut/DocVQA

**Comment by DhavalWI** [comment]
> See my notebooks here: https://github.com/NielsRogge/Transformers-Tutorials/tree/master/Donut/DocVQA

Thanks for the help. I will definitely try this one out.
