### ISSUE TITLE
Nougat ver 0.1.15 & 0.1.16 not utilizing GPU in Colab

### ISSUE THREAD

**Issue by tsycstang** [facebookresearch/nougat#137]
In Google Colab with T4 GPU, newer 0.1.15 & 0.1.16 version do not detect and utilize GPU correctly and fall back to CPU in command line mode, api mode not tested.

My temporary fix is:
!pip install nougat-ocr==0.1.14

**Comment by MereHappyJaZZ** [comment]
Same issue on windows, works by going back to 0.1.14

**Comment by lukas-blecher** [comment]
Thank you, fixed now.
