### ISSUE TITLE
Nougat OCR does not recognize all UTF-8 Encoding characters

### ISSUE THREAD

**Issue by nekiee13** [facebookresearch/nougat#139]
Nougat OCR  does not recognize Š,š,Č,č,Ž,ž which are all part of UTF-8 Encoding. Is there some extra argument that should be passed, related to specific language - like Slovenian or Croatian or enforce the usage of UTF-8?

**Comment by lukas-blecher** [comment]
This is due to the fact that nougat can not understand other languages than english because of the data it was trained on.
Sorry about that
