### ISSUE TITLE
How to delete downloaded model?

### ISSUE THREAD

**Issue by Unturned3** [facebookresearch/nougat#167]
It seems like the nougat command downloads a ~900M pretrained model when it is run for the first time.

Where is this model stored? I'd like to remove it to save disk space as I'm no longer using the nougat tool.

Thanks.

**Comment by wodin** [comment]
Not sure about that, but I created a virtualenv for nougat and for me it contains this:
```
    3.9 GiB [######### ] /lib                                                   
```
That contains `python3.10` which contains `site-packages` and the top of the list of contents there is the following:
```
    2.4 GiB [##########] /nvidia
  949.2 MiB [###       ] /torch
  133.8 MiB [          ] /triton
   63.2 MiB [          ] /pyarrow
   51.8 MiB [          ] /scipy
```

**Comment by lukasherz** [comment]
At least on MacOS, it's stored at: `/Users/<user>/.cache/torch/nougat-0.1.0-<model>`

**Comment by wodin** [comment]
It's similar on Linux:
`~/.cache/torch/hub/nougat-0.1.0-*`

So it might be adhering to the [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html)

See also: https://wiki.archlinux.org/title/XDG_Base_Directory

I haven't checked if the `$XDG_CACHE_HOME` environment variable affects the location, though.

**Comment by Unturned3** [comment]
> At least on MacOS, it's stored at: `/Users/<user>/.cache/torch/nougat-0.1.0-<model>`

Yup, thanks! Probably should include this somewhere in the docs, in case people want to free up disk space.
