### ISSUE TITLE
Latex to PDF

### ISSUE THREAD

**Issue by Stinky-Tofu** [facebookresearch/nougat#182]
Can you release the tool that convert LaTeX to PDF for creating training datasets.

**Comment by lukas-blecher** [comment]
We never did that since arxiv has both, Latex source and pdf already compiled. 
But in general that could be done by any latex tool like texlive

**Comment by Stinky-Tofu** [comment]
> We never did that since arxiv has both, Latex source and pdf already compiled. But in general that could be done by any latex tool like texlive

Thank you for your reply. However, we noticed that the data provided by arXiv separates PDF and LaTeX files, and there are only approximately 600,000 successful pairings of PDFs and LaTeX files. Therefore, I assumed that you recompiled all of them after downloading the LaTeX files. Could you please let me know where you obtained the 1.7 million matched pairs of PDFs and LaTeX files?
