### ISSUE TITLE
Dataset creation: Do we expect the .tex files to be just a single file for each corresponding PDF? 

### ISSUE THREAD

**Issue by sakshaminboson** [facebookresearch/nougat#198]
Hey, 

Thank you for your work, the results are pretty cool! 

I am trying to reproduce your work for a personal project, but it seems for dataset generation many times in the src downloaded from Arxiv  there are many .tex files, I can always merge into a single .tex files maybe using a simple script, so my question is do you expect only a single tex file converted to HTML using LATExml for each pdf? 

Best,
Saksham

**Comment by lukas-blecher** [comment]
We are using engrafo to convert latex project directories to a single html file

**Comment by sakshaminboson** [comment]
Thanks this was really helpful!
