### ISSUE TITLE
any pretrained model ?

### ISSUE THREAD

**Issue by zwysophon** [facebookresearch/nougat#2]

**Comment by lukas-blecher** [comment]
Hello,

yes we released the model weights here on GitHub in the release section:
[https://github.com/facebookresearch/nougat/releases](https://github.com/facebookresearch/nougat/releases/)

The weights are also downloaded automatically at the first execution.

Best,
Lukas

**Comment by XFastDataLab** [comment]
After we testing Nougat, it is found that Nougat seems do not support extracting equation from image, only it works for pdf files ?

**Comment by lukas-blecher** [comment]
> After we testing Nougat, it is found that Nougat seems do not support extracting equation from image, only it works for pdf files ?

This is not related to this issue. And if you decide to open a new issue, please be more specific. Nougat converts the pdf to an image, so it does work only with images. But these images have to be similar to a document page.
