### ISSUE TITLE
Document solution to `No GPU found. Conversion on CPU is very slow.`

### ISSUE THREAD

**Issue by Vuizur** [facebookresearch/nougat#21]
I think it would be cool to add information to the "Install" section of the README that in order to use the GPU, one needs to install CUDA 11.7 or 11.8 and pytorch according to https://pytorch.org/get-started/locally/ (so something like `pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu117`) on Windows before running `pip install nougat-ocr` (which otherwise installs only the CPU versions). I don't know though if these steps are only needed on Windows or also on other platforms.

Thanks a lot for developing this, it performs much better than the previous stuff I dabbled with.

**Comment by Etoile04** [comment]
I agree with that. And how to reinstall in order to enable the GPU ? I tried to reinstall but there is still no GPU found.

**Comment by Vuizur** [comment]
I think you need to `pip uninstall torch` (and the same for torchvision) before installing them again from the pytorch index.

**Comment by lukas-blecher** [comment]
I've added a notice in the readme

**Comment by Vuizur** [comment]
@lukas-blecher Thanks a lot!
