### ISSUE TITLE
Can it be used to ocr non-English text?

### ISSUE THREAD

**Issue by nissansz** [facebookresearch/nougat#3]
Can it be used to ocr non-English text?

**Comment by lukas-blecher** [comment]
We've done some experiments with other Latin-based languages. The results were mostly satisfactory, although any special characters from these languages will be replaced with
the closest equivalent from the Latin alphabet. 
Non-Latin script languages are not supported by the training set at all, so it won't work in these cases

**Comment by nissansz** [comment]
For text line position detection, is mupdf better than cptn?

**Comment by lukas-blecher** [comment]
I have no insight on that matter. We are not performing a text detection step
