### ISSUE TITLE
what is the version of pytorch_lighting?

### ISSUE THREAD

**Issue by FanqingM** [facebookresearch/nougat#32]
The latest pytorch_lighting does not have params such as resume_from_checkpoint and gpus. Could you tell me the version of the pytorch_lighting you use? Moreover, could you give a requirement.txt for this repo?

**Comment by DonMiller9294** [comment]
Hey there! It's awesome that you're diving into your project with `pytorch_lightning`. To check the version you're currently using, you can run a quick command:


pip show pytorch-lightning


This will give you all the details, including the version.

Now, for creating a `requirements.txt` file, you're on the right track. This file helps ensure that your project is consistent and reproducible. To generate it, just use this command:


pip freeze > requirements.txt

And voilà! You'll have a neat `requirements.txt` file listing all the packages and their versions in your environment.

Feel free to update this file whenever you add new packages or want to specify a particular version. It's your project's blueprint for a smooth journey. If you have more questions or need assistance with anything else, don't hesitate to ask!

**Comment by lukas-blecher** [comment]
Hi @FanqingM, thanks for opening the issue.
I have just updated the repository to >=lightning2.0
The requirements are all in the setup.py
