### ISSUE TITLE
no result

### ISSUE THREAD

**Issue by Ying-Zi66** [facebookresearch/nougat#35]
i use this model to convert pdf into mmd，but the mmd is [MISSING_PAGE_EMPTY:1]。no result

**Comment by Ying-Zi66** [comment]
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
  0%|                                                                                            | 0/1 [00:00<?, ?it/s]WARNING:root:Found repetitions in sample 0
[nltk_data] Error loading words: <urlopen error [Errno 11004]
[nltk_data]     getaddrinfo failed>

**Comment by lukas-blecher** [comment]
> You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Looks like you are loading the model in a weird way. What are you running?

**Comment by Ying-Zi66** [comment]
anaconda prompt 
(base) C:\Users\yingzi>nougat C:\Users\yingzi\Desktop\358.pdf --out C:\Users\yingzi\Desktop

**Comment by lukas-blecher** [comment]
Can you give more information about the pdf? What language is the file in? If it's not english, nougat won't be able to process it

**Comment by Ying-Zi66** [comment]
english,
![image](https://github.com/facebookresearch/nougat/assets/64450726/10f33ab5-db9a-4bc4-a0e4-87e58d638184)
