### ISSUE TITLE
ValueError: batch_size should be a positive integer value, but got batch_size=0

### ISSUE THREAD

**Issue by 18959263172** [facebookresearch/nougat#39]
nougat sd.pdf
WARNING:root:No output directory. Output will be printed to console.
/home/caiyu/miniconda3/lib/python3.11/site-packages/torch/functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3483.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
sampler <torch.utils.data.sampler.SequentialSampler object at 0x7f9a052ef3d0> 0 False
Traceback (most recent call last):
  File "/home/caiyu/miniconda3/bin/nougat", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/caiyu/miniconda3/lib/python3.11/site-packages/predict.py", line 113, in main
    dataloader = torch.utils.data.DataLoader(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/caiyu/miniconda3/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 358, in __init__
    batch_sampler = BatchSampler(sampler, batch_size, drop_last)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/caiyu/miniconda3/lib/python3.11/site-packages/torch/utils/data/sampler.py", line 232, in __init__
    raise ValueError("batch_size should be a positive integer value, "
ValueError: batch_size should be a positive integer value, but got batch_size=0

**Comment by lukas-blecher** [comment]
How much VRAM does your GPU have?

**Comment by 18959263172** [comment]
> How much VRAM does your GPU have?

![image](https://github.com/facebookresearch/nougat/assets/5462271/c999e11c-f8c3-438b-8cac-cd618d061e85)

**Comment by lukas-blecher** [comment]
can you try to run 
```
nougat sd.pdf -b 1
```

**Comment by 18959263172** [comment]
> can you try to run
> 
> ```
> nougat sd.pdf -b 1
> ```

![image](https://github.com/facebookresearch/nougat/assets/5462271/91b23079-dbba-411f-806f-5121a5bb49f3)

**Comment by 18959263172** [comment]
> how much gpu ram this model needed? 
i notice there is another model which is call "small" ,Can I switch to it?

**Comment by lukas-blecher** [comment]
Default is small and I recommend at least 3.5G, so it should work on >=4GB cards

**Comment by Derekmini** [comment]
@18959263172 

Hi,

My GPU VRAM is 3GB, and I encountered the `WARNING:root:GPU VRAM is too small. Computing on CPU.` message. I was able to avoid this situation by modifying the factor in `nougat/utils/device.py` [here](https://github.com/facebookresearch/nougat/blob/47c77d70727558b4a2025005491ecb26ee97f523/nougat/utils/device.py#L14C16-L14C16) (for example, based on my own specific situation, I changed it to 0.33).

And, I am able to use Nougat to convert PDF files to `.mmd` files with GPU.

You can use the following Python script to check the size of your GPU memory and adjust the factor according to your specific situation:

```python
import torch
a = torch.cuda.get_device_properties(0).total_memory
print(a)
b = a / 1024 / 1024 / 1000 * 0.33
print(b)
```

Then, change the factor in `directory-for-packages\Lib\site-packages\nougat\utils.device.py`.

I'm not entirely sure if this method is suitable for you, but I believe it's worth trying. In my tests, it significantly reduced the conversion time.

Good luck.
