### ISSUE TITLE
Any comparisons with commercial software Mathpix

### ISSUE THREAD

**Issue by HaisongDing** [facebookresearch/nougat#4]
Mathpix is one of the leading companies for pdf to latex conversion. It also does pretty well on math equations. Have you conduct any experiments with mathpix so that we can get some idea of how well the model performs?

Mathpix: https://mathpix.com/pdf-to-latex

**Comment by lukas-blecher** [comment]
No, we decided against comparisons to commercial products. 
We do offer a baseline for future research in this direction.
