### ISSUE TITLE
Please tell me how to use the nougat_api interface, what parameters it accepts, and how it can receive requests from other servers?

### ISSUE THREAD

**Issue by songsa1** [facebookresearch/nougat#42]
Please tell me how to use the nougat_api interface, what parameters it accepts, and how it can receive requests from other servers?

**Comment by lukas-blecher** [comment]
Good point, I will add instructions in the README. You can also get the correct documentation if you visit
http://localhost:8503/docs

**Comment by lukas-blecher** [comment]
added instructions in the readme
