### ISSUE TITLE
 什么是时间支持中文？ What is time support for Chinese?

### ISSUE THREAD

**Issue by xiaozhi007** [facebookresearch/nougat#44]
I just tried Nougat, unfortunately it does not support Chinese. When will it be possible to support the conversion of Chinese documents?

**Comment by gk966988** [comment]
why not try to do it yourself?

**Comment by lukas-blecher** [comment]
We are not planning to support more languages at the moment. 
We did not include more languages in the first place because we were not able to find more training data. This has not changed

**Comment by xiaozhi007** [comment]
> We are not planning to support more languages at the moment. We did not include more languages in the first place because we were not able to find more training data. This has not changed

This is a great project, thank you for your reply
