### ISSUE TITLE
How to switch between "0.1.0-small" and "0.1.0-base?

### ISSUE THREAD

**Issue by nil-is-lin** [facebookresearch/nougat#5]
I have tried using nougat 

`nougat .\Nougat- Neural Optical Understanding for Academic Documents.pdf -o ./`

It downloaded the 0.1.0-small version. How can I use the 0.1.0-base version for comparison?

**Comment by lukas-blecher** [comment]
You'll need to manually download the model files from the release section into a separate directory (eg nougat-base) and then provide the path to the model
```
nougat .\Nougat- Neural Optical Understanding for Academic Documents.pdf -o ./ --checkpoint .\nougat-base
```
