### ISSUE TITLE
Pytorch Multi-GPU Support?

### ISSUE THREAD

**Issue by marwinsteiner** [facebookresearch/nougat#50]
I installed pytorch to allow Nougat to work with my GPUs, but unfortunately only one (of two) is being used. How can I get pytorch to access the shared memory as opposed to defaulting to one GPU and using **its** memory?

**Comment by lukas-blecher** [comment]
For inference this is not supported. You can just run one instance per GPU and split the work across them

**Comment by marwinsteiner** [comment]
Ok, thanks.
