### ISSUE TITLE
It doesn't seem to run on macOS?

### ISSUE THREAD

**Issue by zer0yu** [facebookresearch/nougat#6]
Env:
```
OS: macOS 13.4 22F66 x86_64
Host: MacBookPro16,1
Kernel: 22.5.0
CPU: Intel i9-9880H (16) @ 2.30GHz
GPU: Intel UHD Graphics 630, AMD Radeon Pro 55
Memory: 35222MiB / 65536MiB
```

Error
```
WARNING:root:No GPU found. Conversion on CPU is very slow.
/Users/zero/anaconda3/lib/python3.10/site-packages/torch/functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at /Users/runner/work/_temp/anaconda/conda-bld/pytorch_1678402629672/work/aten/src/ATen/native/TensorShape.cpp:3484.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
  0%|                                                     | 0/3 [00:00<?, ?it/s]
```

I'm having some difficulty running nougat on macOS:
1. I found no way to use the GPU AMD Radeon Pro 55 with this program.
2. Even after 10 minutes, there's still no progress bar to display.

**Comment by zer0yu** [comment]
I've figured out the problem, using the CPU for calculations is really slow! 3 hours or so to ocr on an 18 page paper!

**Comment by 0x0-bwu** [comment]
> I've figured out the problem, using the CPU for calculations is really slow! 3 hours or so to ocr on an 18 page paper!

Hi, is there any solution for the 'No GPU found' on macOS? I met the same problem. Thanks a lot~

**Comment by zer0yu** [comment]
There's no way to fix this,  transformer isn't supported for AMD's GPU.

**Comment by lukas-blecher** [comment]
> I've figured out the problem, using the CPU for calculations is really slow! 3 hours or so to ocr on an 18 page paper!

That seems very slow, even for CPU computation. On my laptop I'm getting about 1 page in 40s

**Comment by wind22** [comment]
me too

**Comment by ChloeZhou1997** [comment]
> > I've figured out the problem, using the CPU for calculations is really slow! 3 hours or so to ocr on an 18 page paper!
> 
> That seems very slow, even for CPU computation. On my laptop I'm getting about 1 page in 40s

I set the environment to use CPU and my macbook is M1 MAX, I have been waiting for 10mins for one page and it seems stuck at   return torch.var(self.values, 1) / self.values.shape[1]
