### ISSUE TITLE
MPS accelaration

### ISSUE THREAD

**Issue by joanvelja** [facebookresearch/nougat#61]
Hi all, 
Why is the code not supporting MPS acceleration? Should it work or it has not been implemented quite yet?

**Comment by erip** [comment]
It assumes cuda because of [these](https://github.com/search?q=repo%3Afacebookresearch%2Fnougat%20cuda&type=code). You can submit a PR to fix them.

**Comment by lukas-blecher** [comment]
Yes, please submit a PR. I can't test it locally

**Comment by erip** [comment]
@joanvelja I have created a PR to add MPS support. Feel free to give it a try and please provide feedback as you do in the PR thread.

**Comment by DrMWeigand** [comment]
I tried to add mps support but it seems to be that there are calculations and datatypes used which are currently not supported by apple silicon gpus. In particular, the operator aten::erfinv.out and datatype bfloat16 are not yet supported.

**Comment by nullhook** [comment]
@DrMWeigand Where do you see the usage of erfinv? 

According to this [PR](https://github.com/pytorch/pytorch/pull/101507), erfinv will have the MPS variant soon.

**Comment by erip** [comment]
Aside from bf16 support, the only other issue I ran into was addressed by c02b772.

**Comment by lukas-blecher** [comment]
cool!
What if we don't use bf16 for mps?

**Comment by erip** [comment]
Should be fine if slower

**Comment by erip** [comment]
I had to upgrade to nightly because of unavailability of `aten:roll` in 2.0.1, but with 2.2.0-dev*`... 

Good news: only casting to `bfloat16` when `device.type != "mps"` seems to be running. Bad news: it seems to be running extremely slowly; a 2 page PDF has been decoding for >10 min w/ bs=16. 😄

**Comment by DrMWeigand** [comment]
> @DrMWeigand Where do you see the usage of erfinv?
> 
> According to this [PR](https://github.com/pytorch/pytorch/pull/101507), erfinv will have the MPS variant soon.

It was triggered on line 103 in predict.py:
`model = NougatModel.from_pretrained(args.checkpoint).to(torch.bfloat16)`

leading to the error:

`NotImplementedError: The operator 'aten::erfinv.out' is not currently implemented for the MPS device. If you want this op to be added in priority during the prototype phase of this feature, please comment on https://github.com/pytorch/pytorch/issues/77764. As a temporary fix, you can set the environment variable `PYTORCH_ENABLE_MPS_FALLBACK=1` to use the CPU as a fallback for this op. WARNING: this will be slower than running natively on MPS.`

As written in the error message it can be avoided by setting the stated environment variable to 1. This worked as a workaround but then I was running into the bfloat16 error. However, with the newest version everything seems to be resolved. Was it finally possible to use another type than bfloat16? I was trying to do that but it did not work.

**Comment by erip** [comment]
I take my previous comment back: it seems to have been an unlucky PDF. Running `predict` on my CV yields reasonable speed (and quality). I'll push the most recent changes, but with the caveat that it's only been manually tested on inference using a nightly pytorch. This might only require 2.1.0, but I'm not positive as I haven't tracked down the right commits for MPS operations.

**Comment by kaieberl** [comment]
I am running nougat on an M2 MacBook Air, 8GB RAM, with PyTorch 2.2.0 nightly.
For me, since upgrading nougat-api to the latest version (which uses mps), it is unusable because it tries to allocate >13GB RAM, even when setting --batchsize 1. It was working fine on CPU, with RAM <4GB (although quite slow). Does anyone have the same issue? I am also willing to contribute some code here, if you point me into the right direction.
