### ISSUE TITLE
When specifying the --model option to base model, use 0.1.0-base getting error : unrecognized arguments:

### ISSUE THREAD

**Issue by rohan-paul** [facebookresearch/nougat#75]
As per the Readme file if I run the base model, use 0.1.0-base.

```
$ nougat path/to/file.pdf -o output_directory -m 0.1.0-base
```

Getting `nougat: error: unrecognized arguments: -m 0.1.0-base`

**Comment by lukas-blecher** [comment]
I didn't publish to pypi yet, sorry. I'll do another small update. Try in 15 minutes again
