### ISSUE TITLE
Mmd file marttext cannot be read, mathematical formulas cannot be displayed correctly

### ISSUE THREAD

**Issue by smclh** [facebookresearch/nougat#76]
Hello, thank you very much for sharing the project.

I have some doubts. I am unable to use the markdown editor to open the generated mmd file (I am using marktext and have already added - markdown) and copy the content into it, but the mathematical formula is still unrecognized (cannot be displayed correctly as a formula). How can I handle this issue (I tried Mathmix, but I prefer to use Python to handle them)

**Comment by lukas-blecher** [comment]
1. Try to run with the `--markdown` flag
2. Try to replace the \[ , \( delimiters with $$, $

**Comment by marwinsteiner** [comment]
> Hello, thank you very much for sharing the project.
> 
> I have some doubts. I am unable to use the markdown editor to open the generated mmd file (I am using marktext and have already added - markdown) and copy the content into it, but the mathematical formula is still unrecognized (cannot be displayed correctly as a formula). How can I handle this issue (I tried Mathmix, but I prefer to use Python to handle them)

@smclh you can also get an old version of Typora, back when they didn't require a software key. Then, as Lukas suggested if you need the dollarsign math delimeters you can do a simple regex substitution.

**Comment by uneetkumarsingh** [comment]
You can use mathpix mmd plugin in vscode. https://marketplace.visualstudio.com/items?itemName=mathpix.vscode-mathpix-markdown

**Comment by marwinsteiner** [comment]
@uneetkumarsingh too bad mathpix isn't free anymore.

**Comment by uneetkumarsingh** [comment]
It isn't free I know. But the viewer is free. You can use that viewer to view/render the nougat mmd files.

**Comment by marwinsteiner** [comment]
Sure, but what's the added value vs. Other viewers like Typora? No need for Regex substitution?

**Comment by lukas-blecher** [comment]
For me it's just that VSCode is my default editor for anything text related. So +1 for the MMD extension
Also, tables. I'm not familiar with Typora, but nougat will output latex tables only. They are likely not supported by most other markdown editors. But there are some interfering features, like converting `(c)` to ©.

**Comment by uneetkumarsingh** [comment]
@marwinsteiner Yes, No regex substitution needed. nougat mmd is mathpix Compatibale. Here from the nougat readme:

> the lightweight markup language, mostly compatible with [Mathpix Markdown](https://github.com/Mathpix/mathpix-markdown-it) (we make use of the LaTeX tables).

**Comment by marwinsteiner** [comment]
@uneetkumarsingh that's very cool, I'll have to try it out!

**Comment by marwinsteiner** [comment]
@lukas-blecher maybe you could add a flag like ```--delimeter-dollar``` and all math, inline and blocks will have the dollar delimeter around them, or ```--delimeter-braces``` would simply mean this [] as a math delimeter to eliminate the need to post-process the output with a regex substitution? As far as I can tell this shouldn't be too difficult to implement?
