### ISSUE TITLE
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument weight in method wrapper_CUDA___slow_conv2d_forward)

### ISSUE THREAD

**Issue by peps212** [facebookresearch/nougat#79]
from what I understand the program is using both cpu and gpu to perform calculations, how do I go about fixing this?

**Comment by hamster911** [comment]
Yeah it worked fine a couple hours back. I reinstalled it through pip after that and got the same error. Something probably broke in one of the last few commits.

**Comment by lukas-blecher** [comment]
my mistake. I just pushed an update. Give me a second

**Comment by lukas-blecher** [comment]
fixed in 0.1.7 and [c02b772](https://github.com/facebookresearch/nougat/commit/c02b7720cb9445415b0bf204bab488e829178c7b)
