### ISSUE TITLE
TypeError: BARTDecoder.prepare_inputs_for_inference() got an unexpected keyword argument 'past_key_values'

### ISSUE THREAD

**Issue by lucasjinreal** [facebookresearch/nougat#8]
TypeError: BARTDecoder.prepare_inputs_for_inference() got an unexpected keyword argument 'past_key_values'

**Comment by lukas-blecher** [comment]
What transformers version do you have installed?
Can you share more of the error log please?

**Comment by lucasjinreal** [comment]
4.31 and 4.32 all failed.

Would consider add support for latest transformers?

**Comment by lukas-blecher** [comment]
Yes, I was able to reproduce the issue and fixed it. Will push in a bit

**Comment by lukas-blecher** [comment]
fixed in [2b5fa59](https://github.com/facebookresearch/nougat/commit/2b5fa59a594c37c7bc2e99f735b1cfa80a24152e)

**Comment by lucasjinreal** [comment]
@lukas-blecher Does pypi upgraded as well

**Comment by lukas-blecher** [comment]
Yes
