### ISSUE TITLE
Extracting equation/tables from an image converted to pdf

### ISSUE THREAD

**Issue by JamMaster1999** [facebookresearch/nougat#87]
Hello, 
I am interested in using nougat for a specific equation or table. For example: 
[image test.pdf](https://github.com/facebookresearch/nougat/files/12641472/image.test.pdf)
This is a screenshot of an equation which i have then converted to a pdf. But nougat does not seem to recognize the page and as a result returns an empty .mmd file. 
Is there a work around for this?

**Comment by lukas-blecher** [comment]
Weird, it works for me:
```
INFO:root:Processing file image.test.pdf with 1 pages
MultiHead\((Q,K,V)=\) Concat(head\({}_{1},...,\)head\({}_{\rm h}\))\(W^{O}\)

where head\({}_{\rm i}=\)Attention(\(QW_{i}^{Q},KW_{i}^{K},VW_{i}^{V}\))
```

Can you try
```
nougat image.test.pdf --no-skipping
```
