### ISSUE TITLE
Licensing incompatibility with `pymupdf`

### ISSUE THREAD

**Issue by silvanocerza** [facebookresearch/nougat#90]
I noticed that `nougat` is using a MIT license but depends on `pymupdf` as [specified in `setup.py`](https://github.com/facebookresearch/nougat/blob/f5d2cd525979e24c01c72fe223feff2eda555a0c/setup.py#L57).

Given that `pymupdf` is [licensed as AGPL](https://github.com/pymupdf/pymupdf#license-and-copyright) are you planning to switch to AGPL too or to another PDF library like `xpdf`?

I'd like to build on something with `nougat` but I'd like to understand its correct license.

**Comment by kaieberl** [comment]
Yes it _depends_ on pymupdf, but nougat doesn't include its code. As I understand it, licenses only apply to the provided code itself, not some dependencies.

**Comment by silvanocerza** [comment]
Yup, I investigated a bit, as should I have done before opening this 😅, and that's true. 

Guess I was wrong, thanks and sorry for the annoyance. 🙏

I'll close the issue.

**Comment by lukas-blecher** [comment]
Thanks for confirming.
Just a small note, the code is MIT but the model weights are licensed under CC BY-NC 4.0 (because of the data they were trained with)

**Comment by lukas-blecher** [comment]
To be safe I removed pymupdf as a dependency
